FROM ubuntu:15.10
MAINTAINER Zi Shen Lim <zlim.lnx@gmail.com>

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
        bc \
        gcc \
        gcc-aarch64-linux-gnu \
        git \
        make

